version: '3.9'

volumes:
  mysql-volume:
  mysql-testing:

services:
  app:
    container_name: share_play-app
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./laravel/:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  web:
    container_name: share_play-web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - app
    volumes:
      - ./laravel/:/var/www/html

  db:
    container_name: share_play-db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-volume:/var/lib/mysql


  testdb:
    container_name: share_play-test-db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - ${DB_TESTING_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_TEST_DATABASE}
      MYSQL_USER: ${DB_TEST_USERNAME}
      MYSQL_PASSWORD: ${DB_TEST_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_TEST_ROOT_PASSWORD}
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql-testing:/var/lib/mysql